version: 1
services:
  - type: web
    name: pdf-compare-ai
    runtime: python-3.14
    buildCommand: apt-get update && apt-get install -y tesseract-ocr && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
